name: Ultrapy - CI

on:
  pull_request:
    branches-ignore: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.8.14"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff check
        run: uv run ruff check --output-format=github .

      - name: Run type check
        run: uv run ty check .

      - name: Run tests with coverage
        run: uv run pytest -n auto tests --cov --cov-report=xml --cov-report=term

      - name: Coverage Report as PR Comment
        uses: MishaKav/pytest-coverage-comment@main
        if: github.event_name == 'pull_request'
        with:
          pytest-xml-coverage-path: ./coverage.xml
          title: Coverage Report
          badge-title: Coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
