name: Ultrapy - CI

on:
  pull_request:
    branches: [dev, main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary for fetching tags for CD and versioning

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.8.14"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff check
        run: uv run ruff check --output-format=github .

      - name: Run type check
        run: uv run ty check .

      - name: Run tests
        run: uv run pytest -n auto tests --cov
